// Generated by CoffeeScript 1.10.0
(function() {
  var angularModule;

  angularModule = angular.module("myApp.member", ["ngRoute", "ngResource"]);

  angularModule.config([
    "$routeProvider", function($routeProvider) {
      return $routeProvider.when("/member", {
        templateUrl: "view/member/member.html",
        controller: "MemberCtrl"
      }).when("/member/view/:memberId", {
        templateUrl: "view/member/memberDetail.html",
        controller: "MemberDetailCtrl"
      }).when("/member/regist", {
        templateUrl: "view/member/memberDetail.html",
        controller: "MemberRegistCtrl"
      });
    }
  ]);

  angularModule.factory("MemberSvc", [
    "$http", function($http) {
      return {
        getMemberList: function() {
          return $http({
            cache: false,
            url: "/rest/member",
            data: {
              t: new Date().getMilliseconds()
            },
            method: "GET"
          });
        },
        getDetail: function(id) {
          return $http({
            cache: false,
            url: "/rest/member/" + id,
            data: {
              t: new Date().getMilliseconds()
            },
            method: "GET"
          });
        },
        save: function(method, member) {
          switch (method) {
            case "insert":
              $http.post("/rest/member", member);
              break;
            case "update":
              $http.put("/rest/member", member);
          }
          return $http.post("/rest/member", member);
        }
      };
    }
  ]);

  angularModule.factory("CodeSvc", [
    "$http", function($http) {
      return {
        getCodeList: function() {
          return $http({
            cache: true,
            url: "/rest/codeList",
            data: {
              t: new Date().getMilliseconds()
            },
            method: "GET"
          });
        }
      };
    }
  ]);

  angularModule.controller("MemberCtrl", [
    "$scope", "$rootScope", "$window", "$location", "MemberSvc", "CodeSvc", "$q", function($scope, $rootScope, $window, $location, MemberSvc, CodeSvc, $q) {
      var init;
      $rootScope.backdrop = "backdrop";
      init = function() {
        return selectMenu(1);
      };
      init();

	  $q.all([MemberSvc.getMemberList(), CodeSvc.getCodeList()]).then(function(resultArray) {
	
		db_memberList = resultArray[0].data;
        $scope.code = resultArray[1].data;
		partList = $scope.code.partList;
		
		partList.map(item => {
			item.memberList = [];
		});

		db_memberList.map(member => {			
			index = -1;

			if(member.PHONE_NO == "" || member.PHONE_NO == null)
				member.PHONE_NO = "010-0000-0000"
			if(member.BIRTHDAY == "" || member.BIRTHDAY == null)
				member.BIRTHDAY = "0000-00-00"

			for(i=0; i < partList.length; i++ ){
				if(member.PART_CD == partList[i].PART_CD)
					index = i; 
			}

			if(index > -1) partList[index].memberList.push(member);
		});

		$scope.partList = partList;
        return $rootScope.backdrop = void 0;
      });

      /*MemberSvc.getMemberList().success(function(data) {
		console.log(data);
        $scope.memberList = data;
        return $rootScope.backdrop = void 0;
      });*/

      $scope.detail = function(memberId) {
        return $location.path("/member/view/" + memberId).search({});
      };

      
	  return $scope.regist = function() {
        return $location.path("/member/regist");
      };
    }
  ]);

  angularModule.controller("MemberDetailCtrl", [
    "$scope", "$rootScope", "$window", "$routeParams", "MemberSvc", "$location", "CodeSvc", "$q", function($scope, $rootScope, $window, $routeParams, MemberSvc, $location, CodeSvc, $q) {
      var init;
      $rootScope.backdrop = "backdrop";
      init = function() {
        return selectMenu(1);
      };
      init();
      $q.all([MemberSvc.getDetail($routeParams.memberId), CodeSvc.getCodeList()]).then(function(resultArray) {
        $scope.member = resultArray[0].data.member;
        $scope.attMonthList = getAttMonthList(resultArray[0].data.attMonthList);
        $scope.code = resultArray[1].data;
        if (!$scope.member) {
          $location.path("/member");
        }
        return $rootScope.backdrop = void 0;
      });
      $scope.gotoMemberList = function() {
        return $location.path("/member");
      };
      return $scope.save = function() {
        if ($scope.memberForm.$invalid) {
          return $.notify("이름 혹은 핸드폰 전화번호를 형식에 맞게 입력해주세요.");
        } else {
          $rootScope.backdrop = "backdrop";
          return MemberSvc.save("update", $scope.member).success(function(data) {
            $rootScope.backdrop = void 0;
            $location.path("/member");
            return $.notify("저장되었습니다.");
          });
        }
      };
    }
  ]);

  angularModule.controller("MemberRegistCtrl", [
    "$scope", "$rootScope", "$window", "MemberSvc", "$location", "CodeSvc", "$q", function($scope, $rootScope, $window, MemberSvc, $location, CodeSvc, $q) {
      var init;
      $rootScope.backdrop = "backdrop";
      init = function() {
        return selectMenu(1);
      };
      init();
      $q.all([CodeSvc.getCodeList()]).then(function(resultArray) {
        $scope.code = resultArray[0].data;

		console.log($scope.code);
        $rootScope.backdrop = void 0;
        $scope.member = new Object();
        $scope.member.cPositionCd = $scope.code.cPositionList[0].C_POSITION_CD;
        $scope.member.cPositionNm = $scope.code.cPositionList[0].C_POSITION_NM;
        $scope.member.positionCd = $scope.code.positionList[$scope.code.positionList.length - 1].POSITION_CD;
        $scope.member.positionNm = $scope.code.positionList[$scope.code.positionList.length - 1].POSITION_NM;
        $scope.member.statusNm = $scope.code.statusList[0].STATUS_NM;
        $scope.member.statusCd = $scope.code.statusList[0].STATUS_CD;
        $scope.member.partNm = $scope.code.partList[0].PART_NM;
        return $scope.member.partCd = $scope.code.partList[0].PART_CD;
      });
      $scope.gotoMemberList = function() {
        return $location.path("/member");
      };
      return $scope.save = function() {
        if ($scope.memberForm.$invalid) {
          return $.notify("이름 혹은 핸드폰 전화번호를 형식에 맞게 입력해주세요.");
        } else {
          $rootScope.backdrop = "backdrop";
          return MemberSvc.save("insert", $scope.member).success(function(data) {
            $rootScope.backdrop = void 0;
            $location.path("/member");
            return $.notify("저장되었습니다.");
          });
        }
      };
    }
  ]);

  window.getAttMonthList = function(list) {
    var elm, j, len, month, o, preMonth, result;
    if (!list || list.length === 0) {
      return null;
    }
    result = [];
    preMonth = "";
    o = null;
    for (j = 0, len = list.length; j < len; j++) {
      elm = list[j];
      month = elm.month;
      if (month !== preMonth || o === null) {
        o = {
          month: month,
          data: []
        };
        result.push(o);
      }
      o.data.push(list[i]);
      preMonth = month;
    }
    return result;
  };

}).call(this);
