// Generated by CoffeeScript 1.10.0
(function() {
  var angularModule, modules;

  modules = ["myApp.main", "myApp.member", "myApp.att", "myApp.rank", "myApp.info", "ngAnimate", "ngRoute", "ngResource"];

  angularModule = angular.module("myApp", modules);

  angularModule.run(function($rootScope) {
    return $rootScope.$on("$routeChangeStart", function() {
      $rootScope.backdrop = void 0;
      if (document) {
        return document.body.scrollTop = 52;
      }
    });
  });

  angularModule.config([
    "$resourceProvider", function($resourceProvider) {
      return $resourceProvider.defaults.stripTrailingSlashes = false;
    }
  ]);

  angularModule.config([
    "$routeProvider", function($routeProvider) {
      return $routeProvider.otherwise({
        redirectTo: "/main"
      });
    }
  ]);

  window.selectMenu = function(i) {
    $("#navbar li").removeClass("active");
    return $("#navbar li:eq(" + i + ")").addClass("active");
  };

  $(function() {
    $("#navbar li").click(function() {
      $("#navbar li").removeClass("active");
      return $(this).addClass("active");
    });
    return $(".navbar-brand").click(function() {
      if ($("#navbar").hasClass("in")) {
        $(".navbar-toggle:visible").click();
      }
      $("#navbar li").removeClass("active");
      return selectMenu(0);
    });
  });

  $(document).on("click", "#navbar[class='navbar-collapse collapse in'] li", function() {
    return $(".navbar-toggle:visible").click();
  });

}).call(this);

//# sourceMappingURL=app.js.map
