// Generated by CoffeeScript 1.10.0
(function() {
  var angularModule;

  angularModule = angular.module("myApp.part", ["ngRoute"]);

  angularModule.config([
    "$routeProvider", function($routeProvider) {
      return $routeProvider.when("/part", {
        templateUrl: 'view/part/part.html',
        controller: 'PartCtrl'
      });
    }
  ]);

  angularModule.factory("PartSvc", [
    "$http", function($http) {
	  const PREFIX_API = "/api/part"
      return {
        getEventList: $http.createGetRequestFn(PREFIX_API + "/list"),
      };
    }
  ]);

  angularModule.controller("PartCtrl", [
    "$scope", "$rootScope", "PartSvc", function($scope, $rootScope, PartSvc) {
		var events = []


		return PartSvc.getEventList().success(function(event_list) {		
			console.log(event_list)
			event_list.member.map(function(event){
				event.color = '#257e4a';
				event.start = "2019-" + event.BIRTHDAY.substr(5);
				event.title = event.MEMBER_NAME + "생일"
				events.push(event);			
			})

			event_list.worship.map(function(event){
				event.color = "#ff9f89"

				if(event.TTILE=="")
					event.TTILE = "주일예배"
				//event.start = "2019-" + event.start.substr(5);
				events.push(event);			
			})

			$('#part').fullPart({
				header: {
					left: 'prev,next today',
					center: 'title',
					right: 'month,basicWeek'
				},
				aspectRatio: 1,
				weekends: true,
				fixedWeekCount: false,
				businessHours: false, // display business hours
				defaultDate: '2019-01-12',
				navLinks: false, // can click day/week names to navigate views
				editable: true,
				eventLimit: true, // allow "more" link when too many events
				events: events
			});

			return $rootScope.backdrop = void 0;
		});
    }
  ]);

}).call(this);
