// Generated by CoffeeScript 1.10.0
(function() {
  var angularModule;

  angularModule = angular.module("myApp.part", ["ngRoute"]);
  
  angularModule.config([
    "$routeProvider", function($routeProvider) {
      return $routeProvider.when("/part", {
        templateUrl: 'view/part/part.html',
        controller: 'PartCtrl'
      });
    }
  ]);

  angularModule.factory("PartSvc", [
    "$http", function($http) {
	  const PREFIX_API = "/api/part"
      return {
        getPartList: $http.createGetRequestFn(PREFIX_API + "/list"),
        updatePartName: function(part_cd, part_name) {
          return $http.createPostRequestFn(PREFIX_API + "/part_name")({
            PART_NAME: part_name,
            PART_CD: part_cd
          });
        },
        updateTeacherName: function(part_cd, teacher_name) {
          return $http.createPostRequestFn(PREFIX_API + "/teacher_name")({
            TEACHER_NAME: teacher_name,
            PART_CD: part_cd
          });
        },
        createPart: function(part_name, teacher_name, orderby_no) {
          return $http.createPutRequestFn(PREFIX_API)({
            TEACHER_NAME: teacher_name,
            PART_NAME: part_name, 
            ORDERBY_NO: orderby_no
          });
        },
        deletePart: function(part_cd) {
          return $http.createDeleteRequestFn(PREFIX_API)(part_cd);
        },       

      };
    }
  ]);

  angularModule.controller("PartCtrl", [
    "$scope", "$rootScope", "PartSvc","MemberSvc", "$q", function($scope, $rootScope, PartSvc, MemberSvc,  $q) {
    var events = []
    
    $scope.newPart = {
      PART_NAME : "",
      PART_TEACHER : ""
    }

    $scope.change = function(type, part, value) {

      if(type == "part_name") 
        return PartSvc.updatePartName(part, value).success(() => $rootScope.backdrop = void 0)
      
      if(type == "teacher_name") 
        return PartSvc.updateTeacherName(part, value).success(() => $rootScope.backdrop = void 0)
    };

    $scope.create = function(part_name, teacher_name) {   
      return PartSvc.createPart(part_name, teacher_name, $scope.partList.length).success((part) => {
        $scope.partList.push(part)
        $scope.newPart = {
          PART_NAME : "",
          PART_TEACHER : ""
        }
        $rootScope.backdrop = void 0
      })
    };

    $scope.delete = function(part_cd) {
      return PartSvc.deletePart(part_cd).success((part) => {
        const idx = $scope.partList.findIndex((part) => {return part.PART_CD === part_cd}) // findIndex = find + indexOf
        if (idx > -1) $scope.partList.splice(idx, 1)
      })
    }

		return PartSvc.getPartList().success((data) => { 
      $scope.partList = data;
      
      
			return $rootScope.backdrop = void 0;
		});
    }
  ]);

}).call(this);


